version: '3.9'
services:
    db:
        container_name: 'database-project'
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: project
            POSTGRES_USER: project
            POSTGRES_PASSWORD: root

    java-backend:
        container_name: 'java-backend'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - db